### ISSUE TITLE
New name for the project?

### ISSUE THREAD

**Issue by ahoneybun** [cosmic-utils/cosmic-weather#5]
I think this would be neat and would tie into space perhaps?:

- Meteorologist
- Stargazer

**Comment by edfloreshz** [comment]
- Forecast
- Sunny
- Skies
- Moonsoon

**Comment by jwestall** [comment]
I am completely open to a rename to fit the starship theme. I can run a poll on Mastodon if that is acceptable?

**Comment by jwestall** [comment]
Opened poll here: https://mathstodon.xyz/@jwestall_com/113075262286927541

**Comment by ahoneybun** [comment]
> I am completely open to a rename to fit the starship theme. I can run a poll on Mastodon if that is acceptable?

Sounds good to me!

**Comment by jwestall** [comment]
Poll closed with the new name chosen to be Forecast. Will update the app to reflect that.
